# Generated by Django 4.0.3 on 2022-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_recipe_slug_alter_category_image_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=80, verbose_name='Slug'),
        ),
    ]
