version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes: 
      - ./pgdb:/var/lib/postgresql/data
    ports: 
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: user
      POSTGRES_DB: tech

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080